<?php

namespace Ideo\DashBundle\Repository;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{
    public function findContratById($id)
    {
        $requete = $this->getEntityManager()->createQuery('SELECT c FROM IdeoDashBundle:contrat c WHERE c.id = ?1');
        $requete->setParameter(1,$id);
        return $requete->getResult();
    }
}
